version: 0.2

env:
  variables:
    PEM_KEY: "/root/.ssh/key"

proxy:
  logs: yes

phases:
  install:
    commands:
      - sh buildspec/install.sh

  build:
    commands:
      - sh buildspec/build.sh

  post_build:
    commands:
      - sh buildspec/post_build.sh

cache:
  paths:
    - frontend/node_modules/**/*
    - frontend/.next/**/*
    - /root/go/pkg/mod/**/*
    - /root/.cache/go-build/**/*
