INSERT INTO muscle (url, name) VALUES
  ('https://www.muscleandstrength.com/store/landing/jun9protein','Abductors'), 
  ('https://www.muscleandstrength.com/exercises/abs','Abs'),
  ('https://www.muscleandstrength.com/exercises/adductors.html','Adductors'),
  ('https://www.muscleandstrength.com/exercises/biceps','Biceps'),
  ('https://www.muscleandstrength.com/exercises/calves','Calves'),
  ('https://www.muscleandstrength.com/exercises/chest','Chest'),
  ('https://www.muscleandstrength.com/exercises/forearms','Forearms'),
  ('https://www.muscleandstrength.com/exercises/glutes','Glutes'),
  ('https://www.muscleandstrength.com/exercises/hamstrings','Hamstrings'),
  ('https://www.muscleandstrength.com/exercises/hip-flexors','Hip Flexors'),
  ('https://www.muscleandstrength.com/exercises/it-band','IT Band'),
  ('https://www.muscleandstrength.com/exercises/lats','Lats'),
  ('https://www.muscleandstrength.com/exercises/lower-back','Lower Back'),
  ('https://www.muscleandstrength.com/exercises/middle-back','Upper Back'),
  ('https://www.muscleandstrength.com/exercises/neck.html','Neck'),
  ('https://www.muscleandstrength.com/exercises/obliques','Obliques'),
  ('https://www.muscleandstrength.com/exercises/palmar-fascia','Palmar Fascia'),
  ('https://www.muscleandstrength.com/exercises/plantar-fascia','Plantar Fascia'),
  ('https://www.muscleandstrength.com/exercises/quads','Quads'),
  ('https://www.muscleandstrength.com/exercises/shoulders','Shoulders'),
  ('https://www.muscleandstrength.com/exercises/traps','Traps'),
  ('https://www.muscleandstrength.com/exercises/triceps','Triceps'),
  ('https://www.muscleandstrength.com/workout-routines','Dumbbell Exercises'),
  ('https://www.muscleandstrength.com/exercises/barbell','Barbell Exercises'),
  ('https://www.muscleandstrength.com/exercises/bodyweight','Bodyweight Exercises'),
  ('https://www.muscleandstrength.com/exercises/cable','Cable Exercises'),
  ('https://www.muscleandstrength.com/exercises/machine','Machine Exercises'),
  ('https://www.muscleandstrength.com/exercises/exercise-ball','Exercise Ball Exercises'),
  ('https://www.muscleandstrength.com/exercises/ez-bar','EZ Bar Exercises'),
  ('https://www.muscleandstrength.com/exercises/compound','Compound Exercises'),
  ('https://www.muscleandstrength.com/exercises/isolation','Isolation Exercises');
