CREATE TYPE repstyle AS ENUM ('burnout','light','heavy','medium','dropset','timed','failure');

CREATE TABLE rep (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  style repstyle NOT NULL,
  difficulty INT NOT NULL
);

INSERT INTO rep (id,style,difficulty) VALUES 
  (1,'light',1),(2,'light',1),(3,'light',1),(4,'light',1),
  (5,'heavy',1),(6,'heavy',1),(7,'heavy',1),(8,'heavy',1),
  (9,'medium',1),(10,'medium',1),(11,'medium',1),(12,'medium',1),
  (13,'burnout',3),(14,'burnout',2),(15,'burnout',2),(16,'burnout',3),
  (17,'dropset',3),(18,'dropset',2),(19,'dropset',2),(20,'dropset',1),
  (21,'timed',1),(22,'timed',2),(23,'timed',2),(24,'timed',3),
  (25,'failure',1);

CREATE TABLE reppart (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  rep BIGINT NOT NULL REFERENCES rep(id) ON DELETE CASCADE,
  amount INT,
  position INT NOT NULL,
  UNIQUE (rep,position)
);

INSERT INTO reppart (rep,amount,position) VALUES
  -- light
  (1,15,1),(2,20,1),(3,25,1),(4,30,1),
  -- heavy
  (5,2,1),(6,4,1),(7,5,1),(8,6,1),
  -- medium
  (9,6,1),(10,8,1),(11,10,1),(12,12,1),
  -- burnout
  (13,10,1),(13,9,2),(13,8,3),(13,7,4),(13,6,5),(13,5,6),(13,4,7),(13,3,8),(13,2,9),(13,1,10),
  (14,10,1),(14,8,2),(14,6,3),(14,4,4),(14,2,5),
  (15,4,1),(15,6,2),(15,8,3),(15,10,4),(15,12,5),
  (16,1,1),(16,2,2),(16,3,3),(16,4,4),(16,5,5),(16,6,6),(16,7,7),(16,8,8),(16,9,9),(16,10,10),
  -- dropset
  (17,5,1),(17,null,2),(17,null,3),(17,null,4),(17,null,5),(17,null,6),
  (18,10,1),(18,null,2),(18,null,3),(18,null,4),
  (19,8,1),(19,null,2),(19,null,3),(19,null,8),
  (20,15,1),(20,null,2),(20,null,3),
  -- timed
  (21,45,1),(22,60,1),(23,90,1),(24,120,1),
  -- failure
  (25,null,1);

CREATE TABLE block (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  difficulty INT NOT NULL,
  bodyweight boolean NOT NULL DEFAULT false,
  highreps boolean NOT NULL DEFAULT false,
  timed boolean NOT NULL DEFAULT false,
  failure boolean NOT NULL DEFAULT false
);

INSERT INTO block (id,difficulty,bodyweight,highreps,timed,failure) VALUES 
  -- easy
  (1,1,'t','f','f','f'),
  (2,1,'t','t','f','f'),
  (3,1,'t','f','t','f'),
  (4,1,'f','f','f','t'),
  (5,1,'f','f','f','f'),
  (6,1,'f','f','f','f'),
  (7,1,'f','f','f','f'),
  (8,1,'f','f','f','f'),
  -- medium
  (9,2,'t','f','f','f'),
  (10,2,'t','t','f','f'),
  (11,2,'t','f','t','f'),
  (12,2,'f','f','f','t'),
  (13,2,'f','f','f','f'),
  (14,2,'f','f','f','f'),
  (15,2,'f','f','f','f'),
  (16,2,'f','f','f','f'),
  -- hard
  (17,3,'t','f','f','f'),
  (18,3,'t','t','f','f'),
  (19,3,'t','f','t','f'),
  (20,3,'f','f','f','t'),
  (21,3,'f','f','f','f'),
  (22,3,'f','f','f','f'),
  (23,3,'f','f','f','f'),
  (24,3,'f','f','f','f'),
  -- insane
  (25,4,'t','f','f','f'),
  (26,4,'t','t','f','f'),
  (27,4,'t','f','t','f'),
  (28,4,'f','f','f','t'),
  (29,4,'f','f','f','f'),
  (30,4,'f','f','f','f'),
  (31,4,'f','f','f','f'),
  (32,4,'f','f','f','f');

CREATE TABLE blockrep (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  block BIGINT NOT NULL REFERENCES block(id) ON DELETE CASCADE,
  rep BIGINT NOT NULL REFERENCES rep(id) ON DELETE CASCADE,
  position INT NOT NULL,
  UNIQUE (block,position)
);

INSERT INTO blockrep (block,rep,position) VALUES 
  -- easy
  (1,10,1),(1,10,2),(1,10,3),
  (2,1,1),(2,1,2),(2,1,3),
  (3,21,1),(3,21,2),(3,21,3),
  (4,25,1),(4,25,2),(4,25,3),
  (5,7,1),(5,7,2),(5,7,3),
  (6,12,1),(6,11,2),(6,10,3),
  (7,10,1),(7,10,2),(7,18,3),
  (8,11,1),(8,11,2),(8,14,3),
  -- medium
  (9,11,1),(9,11,2),(9,11,3),(9,11,4),
  (10,2,1),(10,2,2),(10,2,3),(10,2,4),
  (11,22,1),(11,22,2),(11,22,3),(11,22,4),
  (12,25,1),(12,25,2),(12,25,3),(12,25,4),
  (13,7,1),(13,7,2),(13,7,3),(13,7,4),
  (14,12,1),(14,11,2),(14,10,3),(14,9,4),
  (15,11,1),(15,11,2),(15,11,3),(15,15,4),
  (16,8,1),(16,6,2),(16,5,3),(16,17,4),
  -- hard
  (17,12,1),(17,12,2),(17,12,3),(17,12,4),(17,12,5),
  (18,3,1),(18,3,2),(18,3,3),(18,3,4),(18,3,5),
  (19,23,1),(19,23,2),(19,23,3),(19,23,4),(19,23,5),
  (20,25,1),(20,25,2),(20,25,3),(20,25,4),(20,25,5),
  (21,7,1),(21,7,2),(21,7,3),(21,7,4),(21,7,5),
  (22,12,1),(22,11,2),(22,10,3),(22,9,4),(22,17,5),
  (23,7,1),(23,7,2),(23,7,3),(23,7,4),(23,17,5),
  (24,11,1),(24,11,2),(24,13,3),(24,16,4),
  -- insane
  (25,1,1),(25,1,2),(25,1,3),(25,1,4),(25,1,5),(25,1,6),
  (26,4,1),(26,4,2),(26,4,3),(26,4,4),(26,4,5),(26,4,6),
  (27,24,1),(27,24,2),(27,24,3),(27,24,4),(27,24,5),(27,24,6),
  (28,25,1),(28,25,2),(28,25,3),(28,25,4),(28,25,5),(28,25,6),
  (29,7,1),(29,7,2),(29,7,3),(29,7,4),(29,7,5),(29,7,6),
  (30,7,1),(30,7,2),(30,7,3),(30,7,4),(30,14,5),(30,15,6),
  (31,9,1),(31,10,2),(31,11,3),(31,12,4),(31,16,5),(31,13,6),
  (32,5,1),(32,6,2),(32,7,3),(32,8,4),(32,10,5),(32,11,6);
